POST http://localhost:3333/events
Content-Type: application/json

{
   "title": "Novo Evento",
   "details": "um evento muito legal",
   "maximumAttendees": 1
}

###

POST http://localhost:3333/events/6465826f-e240-40b2-8e97-91134cbfd55f/attendees
Content-Type: application/json

{
   "name": "Johnn Doe",
   "email": "agate34t5@gmail.com"
}

###

GET http://localhost:3333/events/6465826f-e240-40b2-8e97-91134cbfd55f


###

GET http://localhost:3333/attendees/5/badge
